#!/bin/sh
#
# Startup / shutdown script for the piped daemon
#
# Copyright (c) 2011, FunPlus, Inc.
# All rights reserved
#
#
### BEGIN INIT INFO
# Provides:          piped
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $named
# Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    piped daemon
# Description:          piped daemon

### END INIT INFO

. /etc/init.d/functions

if [ "$(id -u)" != "0" ]; then
    echo "Must run as root"
    exit 1
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

PIPED_HOME=/var/wd/piped
DAEMON=$PIPED_HOME/bin/piped
PIDFILE=$PIPED_HOME/var/piped.pid
CONFIGFILE=$PIPED_HOME/etc/piped.cf
LOGFILE=$PIPED_HOME/var/piped.log
CRASHLOG=$PIPED_HOME/panic.dump
LOCKFILE=$PIPED_HOME/var/piped.lock

test -f $DAEMON || exit 0
test -f $CONFIGFILE || exit 0

# Otherwise, RHEL (and apparently Fedora) tries to "help" and set soft
# limit of core file size to 0 for daemons. It's done as part of
# daemon shell function shortly after changing user. See MB-6601
DAEMON_COREFILE_LIMIT=unlimited

start() {
    touch $PIDFILE 
    cd $PIPED_HOME
    ulimit -n 40960
    ulimit -c unlimited
    ulimit -l unlimited
    daemon --pidfile PIDFILE "/usr/sbin/daemonize $DAEMON -conf $CONFIGFILE -crashlog $CRASHLOG -log $LOGFILE -lockfile $LOCKFILE -level trace"
    errcode=$?
    return $errcode
}

stop() {
    daemon "$DAEMON -k -lockfile $LOCKFILE -conf $CONFIGFILE"
    errcode=$?
    return $errcode
}

running() {
    pidofproc -p $PIDFILE $DAEMON >/dev/null
    errcode=$?
    return $errcode
}

case $1 in
    start)
        if running ; then
            warning && echo "piped-daemon is already started"
            exit 0
        fi
        echo -n $"Starting piped-daemon"
        start
        echo
        ;;
    stop)
        echo -n $"Stopping piped-daemon"
        stop
        echo
        ;;
    restart)
        echo -n $"Stopping piped-daemon"
        stop
        echo
        echo -n $"Starting piped-daemon"
        start
        echo
        ;;
    status)
        if running ; then
            echo "piped-daemon is running"
            exit 0
        else
            echo "piped-daemon is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/piped {start|stop|restart|status}" >&2
        exit 3
esac
